### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by byrman** [SectorLabs/django-postgres-extra#103]
We use Django in a multiple-database setup (2 databases). The default and non-default database require "django.contrib.gis.db.backends.postgis" and "psqlextra.backend", respectively. Upon initialization, however, PostgresManager performs a hard-coded check on the ENGINE of the default database:

https://github.com/SectorLabs/django-postgres-extra/blob/master/psqlextra/manager/manager.py#L23

It seems that a more flexible approach is needed to support multiple databases.

**Comment by eugene-kulak** [comment]
+1, It would be nice if this package can fallback to the default implementation, so it can be used with different backend (Oracle, MySQL)

**Comment by atul-bhouraskar** [comment]
Raised a pull request that could fix this issue, see #113

**Comment by Photonios** [comment]
Basic support for this has landed in v2.0.1 thanks to a contribution by @atul-bhouraskar. Please open a new issue for more extended support.
