### ISSUE TITLE
Overly specific dependencies

### ISSUE THREAD

**Issue by alxnik** [SectorLabs/django-postgres-extra#124]
When installing the package from pypi, I get the following error:
`ERROR: django-postgres-extra 2.0.2 has requirement python-dateutil==2.8.0, but you'll have python-dateutil 2.8.1 which is incompatible.`

Although the version dependency in understandable, the minor version pinning can potentially create issues with updating to bug fixing updates

**Comment by Photonios** [comment]
This has been fixed: https://github.com/SectorLabs/django-postgres-extra/commit/071e184a7c550cd6f9362a2ad278f5a5d5776927

It'll be in the next release :)
