### ISSUE TITLE
[question] Create unique indexes on materialized views

### ISSUE THREAD

**Issue by MicicFilip** [SectorLabs/django-postgres-extra#127]
Hey people, 

Is it possible to define unique constraints option inside `ViewMeta`  in [PostgresMaterializedViewModel](https://github.com/SectorLabs/django-postgres-extra/blob/master/psqlextra/models/view.py#L102)?
Or is there some other way to define these indexes?

Thanks in advance!

**Comment by Photonios** [comment]
This is now supported with `psqlextra.indexes.UniqueIndex`:

```
from psqlextra.indexes import UniqueIndex
from psqlextra.models import PostgresMaterializedViewModel

class MyModelView(PostgresMaterializedViewModel):
    class Meta:
        indexes = [
            UniqueIndex(fields=['name']),
        ]

    class ViewMeta:
        query = MyModel.objects.all()

    name = models.TextField()
```
