### ISSUE TITLE
on_conflict() with action ConflictAction.NOTHING does not utilize the `index_predicate` attribute

### ISSUE THREAD

**Issue by KennyMonster** [SectorLabs/django-postgres-extra#134]
I have a model with the following unique constraint:

```
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['training', 'user'],
                condition=Q(completed__isnull=True),
                name='single_in_progress_session',
            )
        ]
```

I want to get or create an instance of this model atomically, thus I try using `on_conflict` with a `ConflictAction.NOTHING` as I don't actually want to update the row. When I

I try the following query:

```
(
    MyModel.objects
    .on_conflict(['training', 'user'], ConflictAction.NOTHING, index_predicate='completed IS NULL')
    .insert_and_get(training_page=training_page, user=user)
)
```

but it results in the following exception:

`django.db.utils.ProgrammingError: there is no unique or exclusion constraint matching the ON CONFLICT specification`

If I change it to use `ConflictAction.UPDATE` though, the query succeeds.

Works:

```
(
    MyModel.objects
    .on_conflict(['training', 'user'], ConflictAction.UPDATE, index_predicate='completed IS NULL')
    .insert_and_get(training_page=training_page, user=user)
)
```

I've traced the issue to psqlextra/compiler.py:

```
        if self.query.conflict_action.value == "UPDATE":
            return self._rewrite_insert_update(sql, params, returning)
        elif self.query.conflict_action.value == "NOTHING":
            return self._rewrite_insert_nothing(sql, params, returning)
```

The issue seems to be that `self._rewrite_insert_update` makes use of the `index_predicate` attribute, while `self._rewrite_insert_nothing` does nothing with it, thus generating the wrong SQL.

Version used: django-postgres-extra==1.22

**Comment by Photonios** [comment]
2.x handles this properly. Upgrade for the fix.
