### ISSUE TITLE
Add support for ltree columns

### ISSUE THREAD

**Issue by bjmc** [SectorLabs/django-postgres-extra#136]
I found this project while searching for [ltree support](https://www.postgresql.org/docs/current/ltree.html) for Django, because ['ltree' is listed among the keywords](https://github.com/SectorLabs/django-postgres-extra/blob/master/setup.py#L49) in `setup.py` but unless I've missed it, the library doesn't seem to actually offer any ltree features for the Django ORM.

Is ltree support on the roadmap for the future?

**Comment by a3kov** [comment]
https://github.com/mariocesar/django-ltree

**Comment by Photonios** [comment]
The demand for this feature is already documented in #7 , closing this as a duplicate.
