### ISSUE TITLE
Annotation by groups is not working

### ISSUE THREAD

**Issue by joemarct** [SectorLabs/django-postgres-extra#143]
Django supports grouping and annotation per group by simply calling `.values()` first and then `.annotate()` on a queryset. It's been such a handy feature for us. However, this is not working when using `PostgresModel` manager.

Docs:
https://docs.djangoproject.com/en/3.2/topics/db/aggregation/#order-of-annotate-and-values-clauses

Example:
```python
from django.db.models import Sum

# Model
class Transaction(PostgresModel):
    token = models.ForeignKey(Token)  # Foreign key to another table
    wallet_hash = models.CharField(max_length=70)
    amount = models.FloatField()

# Query
Transaction.objects.filter(
    wallet_hash='5557c87e875dec15a813ee2a1c84e672ea034345152d19233ddf9dbb65aa16ed'
).values(
    'token'
).annotate(
    balance=Sum('amount')
)

# Result of query when using PostgresModel
{'token': 980, 'balance_new': 1000.0}
{'token': 7, 'balance_new': 333.0}
{'token': 7, 'balance_new': 399.0}
{'token': 7, 'balance_new': 500.0}

# Result of query when using Django's built in manager
{'token': 980, 'balance': 1000.0}
{'token': 7, 'balance': 1232}
```

In that example, Django's built-in manager groups the query results into individual tokens and computes balance per group. But in `PostgresModel` manager, no such grouping happens, balance annotation is done for each transaction record.

Also, I noticed that the balance annotation becomes `balance_new` when using `PostgresModel` manager, instead of just `balance`.

**Comment by Mogost** [comment]
Try to output SQL queries for both cases. This will make it easier to understand what happened.
```
Transaction.objects.filter(
    wallet_hash='5557c87e875dec15a813ee2a1c84e672ea034345152d19233ddf9dbb65aa16ed'
).values(
    'token'
).annotate(
    balance=Sum('amount')
).query.__str__()
```

**Comment by Photonios** [comment]
Thanks for pointing this out @kozlek! I'll release the official version shortly.
