### ISSUE TITLE
apply a range partition on model which has abstract base classes

### ISSUE THREAD

**Issue by chaoyifei** [SectorLabs/django-postgres-extra#146]
I'm try to apply a range partition on  model C ,How can i use  PostgresPartitioningMethod?
```python
class A(models.Model):
     id=models.AutoField(primary_key=True)
     a= models.Foreignkey(...)
     b=models.Foreignkey(...)
     ...

    class Meta:
        abstract = True

class B(models.Model):
    ...

    class Meta:
        abstract = True

class C(A,B):
    timestamp = models.DataTimeField(auto_created=True)

class D():
     d = models.ForeignKey(C,on_delete=models.CASCADE)
        
```
I'm try to apply  :

```python
class A(models.Model):
     id=models.AutoField(primary_key=True)
     a= models.Foreignkey(...)
     b=models.Foreignkey(...)
     ...

    class Meta:
        abstract = True

class B(models.Model):
    ...

    class Meta:
        abstract = True

class C(A,B,PostgresPartitionModel):
    class PartitioningMeta:
        method = PostgresPartitioningMethod.RANGE
        key=["timestamp"]
    timestamp = models.DataTimeField(auto_created=True)
class D():
     d = models.ForeignKey(C,on_delete=models.CASCADE)
```
Then:
```
    python manage.py pgmakemigrations 
    python manage.py migrate
```
But raise django.db.utils.ProgrammingError: there is no unique constraint matching given keys for referenced table "c"

django version : 3.1.1
pg version : postgres:12-alpine

Why the table "c" has two Primary key : id 、timestamp

Can i use the primary_key like id directly?

**Comment by davmlaw** [comment]
This is not due to abstract base classes, but is due to partition limitations, from the postgres docs:

[Limitations](https://www.postgresql.org/docs/current/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE-LIMITATIONS)

> Unique constraints (and hence primary keys) on partitioned tables must include all the partition key columns

So, your table has a composite primary key (2 columns), and thus any FK to it must also be a composite key of 2 columns. Django does not currently support this.

**Comment by chaoyifei** [comment]
> This is not due to abstract base classes, but is due to partition limitations, from the postgres docs:
> 
> [Limitations](https://www.postgresql.org/docs/current/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE-LIMITATIONS)
> 
> > Unique constraints (and hence primary keys) on partitioned tables must include all the partition key columns
> 
> So, your table has a composite primary key (2 columns), and thus any FK to it must also be a composite key of 2 columns. Django does not currently support this.

I modified the 'https://github.com/SectorLabs/django-postgres-extra/blob/master/psqlextra/backend/schema.py'
```python
    # create a composite key that includes the partitioning key
        sql = sql.replace(" PRIMARY KEY", "")
        sql = sql[:-1] + ", PRIMARY KEY (%s, %s))" % (
            self.quote_name(model._meta.pk.name),
            partitioning_key_sql,
        )

to:
```python

    # create a composite key that includes the partitioning key
        sql = sql.replace(" PRIMARY KEY", "")
        sql = sql[:-1] + ", PRIMARY KEY (%s))" % (
            partitioning_key_sql,
        )
```

then when create table ,it has one primary key(partitioning key),and FK works well.

**Comment by davmlaw** [comment]
But then the foreign key doesn't point to records. I don't understand why that would be a good idea, why would you want to keep track of just the partition? Surely there are many records per partition (justifying use of the partition?)

**Comment by Photonios** [comment]
Since this doesn't point to a bug in django-postgres-extra and there's no more activity here, I am closing this.
