### ISSUE TITLE
Any chance to have the new version released? 

### ISSUE THREAD

**Issue by zhavir** [SectorLabs/django-postgres-extra#156]
is there any chance to release the new version that relax the requirements of python-dateutil? it was previously fixed to version 2.8.1

**Comment by Photonios** [comment]
I've released [2.0.3](https://github.com/SectorLabs/django-postgres-extra/releases/tag/v2.0.3) officially now. There's also [2.0.4rc1](https://github.com/SectorLabs/django-postgres-extra/releases/tag/v2.0.4rc1) that includes new features.
