### ISSUE TITLE
Contributing to django.contrib.postgres

### ISSUE THREAD

**Issue by drewpc** [SectorLabs/django-postgres-extra#16]
Hi!  Great package!  I'm looking at using it for my current project.  Have you considered integrating/contributing some of this code to the Django project so that it's integrated with their django.contrib.postgres module?  BTW, can't wait for the Bulk UPSERT!!!!

https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/

**Comment by Photonios** [comment]
Hi drewpc,

Thanks for the feedback! Glad to hear it's useful to you :-)

We (SectorLabs) also desperately need bulk upserts, and I am working on it. I can't make any promises as to when this going to be done as I maintain this package on company time and sometimes personal time, meaning my time is limited, but I am doing my best to get this done.

On the long-term, I'd love to see some of this stuff to be upstreamed to Django. I'll create an issue to remind myself that I need to research on what the right approach for that is.

Again, thanks for the message. Don't hesitate to submit an issue for a bug or a desired feature.

Cheers!

**Comment by Photonios** [comment]
On a side note, what features are you using from this package? It's important for me to know so that I can focus on not breaking those.

**Comment by drewpc** [comment]
We are using the INSERT ON CONFLICT RETURNING feature.  Being able to do upserts and return the stored row (for example: after an auto incrementing key was saved) in a single query is a great optimization feature.

**Comment by Photonios** [comment]
Cool! That was one of the features that prompted the development of this package.

Any chance we can mention your employer/product/website in the README as one of the users?

**Comment by Photonios** [comment]
@drewpc Bulk upserts have been added in v1.14 :)

https://github.com/SectorLabs/django-postgres-extra/releases/tag/v1.14
