### ISSUE TITLE
Release problem

### ISSUE THREAD

**Issue by benoit9126** [SectorLabs/django-postgres-extra#160]
With the version 2.0.3, there are problems with the [`.tar.gz` archive](https://pypi.org/project/django-postgres-extra/2.0.3/#files):
1. The file is named `django-postgres-extra-2.0.3.macosx-10.15-x86_64.tar.gz`. Its name should have been `django-postgres-extra-2.0.3.tar.gz` (without the macosx reference)
2. This archive contains a bad files structure. It starts with `/./Users/swen/Code/django-postgres-extra/.env/lib/python3.8/site-packages/<...>` while it should have been `/django-postgres-extra-2.0.3/<...>`.

Is it possible to correct the current release or to publish a new release with a correct archive? Thanks

**Comment by Photonios** [comment]
Whoops! Thanks for the heads up. Could you try `2.0.4rc2` ?

**Comment by benoit9126** [comment]
@Photonios It works!

**Comment by Photonios** [comment]
2.0.4 has been released.
