### ISSUE TITLE
How to migrate existing table to use partitioning?

### ISSUE THREAD

**Issue by sknutsonsf** [SectorLabs/django-postgres-extra#164]
What is a method to migrate an existing table to use range partitioning?  Can this be added into the documentation?

My SensorData table has about 400M rows (73gb) so space matters (indexes are about 20gb).   I need to make sure indexes get dropped, then data copied to the new table with partitions, and finally indexes created on the partitioned table.  This needs to happen over several migrations (or a non-atomic migration) so space can be freed.

I've tried a couple of approaches and all seem to fail with some problem around the indexes and ForeignKey constraints.  I really want the final django object and table to end up the same names.

**Comment by satyajitp-navsoft** [comment]
after apply pgmakemigrations i am getting this error please helm me on that
AttributeError: 'MigrationAutodetector' object has no attribute 'new_apps'

**Comment by Photonios** [comment]
This is such a complex problem that it would be dangerous for this package to try to support this. You should solve this outside Django use state-only migration operations to bring Django up to date with reality.
