### ISSUE TITLE
Is there a way to return rows which were inserted vs updated?

### ISSUE THREAD

**Issue by joshuakoh1** [SectorLabs/django-postgres-extra#166]
Ideally the row + bool representing created/updated like update_or_create but any form of distinction would be helpful further processing

**Comment by Photonios** [comment]
No, there is no good way to do this. PostgreSQL simply doesn't return this information. Version 1.x of this package tried some hacks to do this and it caused all sorts of problems and it was removed.

If you really need this, don't use this package and use some raw SQL that caters to your use case.
