### ISSUE TITLE
Issue come when apply partition with **ForeignKey

### ISSUE THREAD

**Issue by adnanrizwee** [SectorLabs/django-postgres-extra#169]
return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: cannot reference partitioned table "core_model1"

Is partition accept foreign key or not? 

@salty-horse @askoretskiy  @ivanp  @roskakori  @AdelaS  @a3kov @adamchainz  @adbuda  @AdeelZahir @BaditaGeorgeSL @berciuliviu @berekmerilorand  @bitaccounts  @camelia-lazar-sl  @cdenis95 @cipix2000  @claudiu-ch  @cozmatudor  @dolhadan  @dragosMC91 @drewpc  @dtoniuc  @dolhadan @elnygren @ericpalakovichcarr @florinroman83  @MrHup

**Comment by salty-horse** [comment]
@adnanrizwee Please don't `@` anyone when opening an issue, or when replying, unless they are already in the discussion.

I'm not involved with this project at all, and find this very annoying.

**Comment by adamchainz** [comment]
Yeah don't spam

**Comment by adnanrizwee** [comment]
is this package support multiple ForeignKey. beacause I am not able to do partition with foreignkey.

**Comment by Photonios** [comment]
Like others mentioned, it is not appropriate to tag random individuals who at some point did some work on this package.

Your question is a bit too vague to be answered and lacks details such as your model set up, stack trace etc. If you are still facing issues, please open a new issue without tagging anyone. I am closing this to avoid further disturbing anyone who was tagged on this issue.
