### ISSUE TITLE
Drop extra dependencies

### ISSUE THREAD

**Issue by Mogost** [SectorLabs/django-postgres-extra#170]
Is it possible to drop from project `ansimarkup` and `colorama` dependencies?
These dependencies are not widely used in the project and do not look very necessary.
It would be great if there was no need to pull these dependencies along with `django-postgres-extra`.

**Comment by Photonios** [comment]
Done here: https://github.com/SectorLabs/django-postgres-extra/commit/6c6f4999fd440a04d0fbc6c0a76644df8ec236bd
