### ISSUE TITLE
Support postgis

### ISSUE THREAD

**Issue by lidyum** [SectorLabs/django-postgres-extra#195]
my postgresql docker **image:postgis/postgis:12-master**

I use **DATABASE_ENGINE=django.contrib.gis.db.backends.postgis**

When this option set as **DATABASE_ENGINE=psqlextra.backend**, it  raises error: 

`AttributeError: 'PostgresOperations' object has no attribute 'geo_db_type'`

**Comment by lidyum** [comment]
sorry!! here is what i was looking for
 https://django-postgres-extra.readthedocs.io/en/master/settings.html

**Comment by bsuhagia** [comment]
@lidyum I tried setting POSTGRES_EXTRA_DB_BACKEND_BASE = django.contrib.gis.db.backends.postgis but I am still getting the same error as you

**Comment by bsuhagia** [comment]
@Photonios could you help with this?

**Comment by bsuhagia** [comment]
Never mind. I had set POSTGRES_EXTRA_DB_BACKEND_BASE incorrectly, within the DATABASE config
