### ISSUE TITLE
Trying to roll back to old engine.

### ISSUE THREAD

**Issue by Wadhah-Sky** [SectorLabs/django-postgres-extra#204]
I faced three major problems with this package:

1- trying to roll back to old engine `django.db.backends.postgresql` impossible unless you delete the entire database.
2-  if you by mistake add `unique=True` to field that doesn't support it, will be nightmare to delete the field and the constraint.
3- the engine `"ENGINE": "psqlextra.backend"` will not works fine if you delete the migrations files and re-run the migration process. 

Thanx.

**Comment by Photonios** [comment]
Switching database back-ends halfway through a project is usually impossible. It is not an issue specific to this project. All your migrations are expected to break if you switch engines as the current engine is not specified in the migration.

The only way to do it is to delete all migrations you created up until now, switch the engine and re-create the initial migration. You cannot not continue to use features from django-postgres-extra if you do this.
