### ISSUE TITLE
Use lock friendly queries for table management in pgpartition command

### ISSUE THREAD

**Issue by rpradal** [SectorLabs/django-postgres-extra#229]
Hello,

On my projet i have a table that is under heavyload. I use time based partitioning to archive old data.
Sometimes when running the `pgpartition` command to create future partitions i end up with a lock error message.
After having a look at the psql partition documentation, it looks like a more lock friendly way of creating a partition is to create to partition first and the attach it later.
Do you think that this is something that could be considered in this library ?

thanks

**Comment by Photonios** [comment]
Yes, that can be considered. Feel free to open a PR 🎉
