### ISSUE TITLE
Django Is their any way to referrence jsonfield of one model into another model?

### ISSUE THREAD

**Issue by pratikjaiswal15** [SectorLabs/django-postgres-extra#26]
Currently I am using jsonfield in a model now I want to use that jsonfield into another model.Is their any way to reference jsonfield of a model into another?
If no, can anyone suggest a better way to do it?

**Comment by Photonios** [comment]
I think this is out of scope for this package. Your question is not related to this package. I think the broader Django community can help you better:

https://docs.djangoproject.com/en/2.0/faq/help/
