### ISSUE TITLE
Using with postgis?

### ISSUE THREAD

**Issue by tony** [SectorLabs/django-postgres-extra#27]
Any instructions for how this would be used alongside postgis?

```
django.core.exceptions.ImproperlyConfigured: 'django.contrib.gis.db.backends.postgis' is not the 'psqlextra.backend'. django-postgres-extra cannot function without the 'psqlextra.backend'. Set DATABASES.ENGINE.
Exception ignored in: <bound method PostgresManager.__del__ of <psqlextra.manager.PostgresManager object at 0x10beb2860>>
```

Is it possible to use this extension with purely the manager, or is the backend a definite requirement?

**Comment by Photonios** [comment]
The back-end is required, but there's an option to make it work with another back-end. We're also using PostGIS. We have a setting:

```
POSTGRES_EXTRA_DB_BACKEND_BASE
```

Set that to PostGIS's back-end should work.
