### ISSUE TITLE
Return multiple rows after bulk_upsert?

### ISSUE THREAD

**Issue by trifle** [SectorLabs/django-postgres-extra#32]
Hi,

(I've read the contributing guidelines and am sketching this out here to potentially work towards a pull request. A 24h reply definitely isn't necessary!)

I would like to do a bulk_upsert and use the returned IDs since it presumably saves a roundtrip.
From my admittedly naïve understanding, this should be possible.

Recapping my reading of the code:
`PostgresQuerySet` has a `bulk_upsert()` method that sets the `on_conflict` parameters.
Then, `bulk_insert` gets the insert compiler and executes it via `compiler.execute_sql(return_id=True)`, which is implemented in the compiler here: https://github.com/SectorLabs/django-postgres-extra/blob/c620fcd8903faeda61bee2a599ed18531f9fbdad/psqlextra/compiler.py#L45

The crucial part is:

```python
        with self.connection.cursor() as cursor:
            rows = []
            for sql, params in self.as_sql(return_id):
                cursor.execute(sql, params)
                rows.append(cursor.fetchone())
```

Now, this *does* return for a bulk_insert. But it only includes one value since `cursor.fetchone()` yields one of the potentially many.

For example, using bulk_upsert code from the documentation yields the following query:

`[('INSERT INTO "pg_mymodel" ("myfield") VALUES (%s), (%s) ON CONFLICT ("myfield") DO UPDATE SET "myfield" = EXCLUDED."myfield" RETURNING *',
  ('beer', 'wine'))]`

This is a list of one query, which returns two IDs (`RETURNING *` gets overridden by `_rewrite_insert
` later on, but that's irrelevant). From this query, cursor.fetchone() places one item in rows, which is then returned.

It should be possible to use `cursor.fetchall()` in case of a bulk upsert (maybe always?), and extend rows instead. That should yield all affected rows. The relevant documentation for `psycopg2's fetchall` is [here](http://initd.org/psycopg/docs/cursor.html#cursor.fetchall).

I'm thinking of something along the lines of:

```python
    def execute_sql(self, return_id=False):
        # execute all the generate queries
        with self.connection.cursor() as cursor:
            rows = []
            for sql, params in self.as_sql(return_id):
                cursor.execute(sql, params)
                rows.extend(cursor.fetchall())
```

I'm definitely no database / Django expert, so I'd be happy about any input and/or criticism here!

**[update]**
Just for completeness' sake: In order to return the values all the way through, the return statement in the manager would need to move one line up:
https://github.com/SectorLabs/django-postgres-extra/blob/c620fcd8903faeda61bee2a599ed18531f9fbdad/psqlextra/manager/manager.py#L156

to read `return compiler.execute_sql(return_id=True)`

**Comment by Photonios** [comment]
https://github.com/SectorLabs/django-postgres-extra/pull/31

This PR takes care of this but needs work. I think the solution in the PR is good. If it gets updated with some tests, then we can merge that :)

**Comment by Photonios** [comment]
This was actually implemented. Note that when you use `.on_conflict()` it will really only return newly inserted rows. Updated rows are not returned.
