### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by seroy** [SectorLabs/django-postgres-extra#39]
With Django 2.0 release we faced with fact that django internal api was changed in some places, so we need to decide about support django 1.x. Three options available:
* drop support for Django 1.x
* make new branch/version 2.0 of `django-postgres-extra`, and backport new features from here to v1
* continue support Django 1.x and add Django 2.0 support with the current version numbering

For first or second option use PR #34, in last case - PR #35.
If last option will be choiced, then tests need be runned against several Django versions for this use PR #38

**Comment by Photonios** [comment]
Hi @seroy 

I don't think dropping support for Django 1.X is a good idea right now. Django 2.0 was only recently released so there are tons and tons of projects out there still using it, including ourselves. I also don't like the idea of maintaining separate versions. On the other hand, maintenance becomes harder when having to support both features.

I am not entirely sure what to do here, but for now I think we'll have to keep Django 1.X support. As soon as Django 2.0 becomes a bit more widespread, then I'll be the first one to call for dropping 1.X support.

I'll have a look at PR #35 and see if I can get #38 merged as well :)

Again, many thanks for the contribution! It's appreciated :)

Cheers from 11.000 feet in the air (on an airplane at the moment) 😄

**Comment by seroy** [comment]
@Photonios, when new version will available on pypi?

**Comment by Photonios** [comment]
@seroy I've created an alpha release on PyPi:

https://pypi.python.org/pypi/django-postgres-extra

We'll run this against some internal projects we have for a while, if everything is ok, I'll release a full version. Please let me know if you notice anything weird with the alpha release :)
