### ISSUE TITLE
PostgresQuerySet.insert assumes the existence of an 'id' field

### ISSUE THREAD

**Issue by PeterJCLaw** [SectorLabs/django-postgres-extra#48]
It should probably use `pk` instead so that it can be used with models whose primary keys are named other than `id`.

**Comment by elnygren** [comment]
Yup, `.insert` is broken if your Model uses something else than 'id' as a primary key. 

For django devs, a quite common usecase might be

```
class Profile
  user = OneToOneField(User, primary_key=True, ....)
```

https://github.com/SectorLabs/django-postgres-extra/blob/master/psqlextra/manager/manager.py#L191
