### ISSUE TITLE
Bulk upserts with F expressions

### ISSUE THREAD

**Issue by tyuo9980** [SectorLabs/django-postgres-extra#51]
My use case includes updating existing field values by applying some math on them(incrementations mostly) or creating the row if it doesnt exist. Is there a way where I can use F expressions to upsert?

**Comment by Photonios** [comment]
Have you tried this? I am not entirely sure, but I think this already works.

**Comment by Photonios** [comment]
Since I haven't heard back about this, I am going to close this issue. Feel free to re-open it if the problem was not resolved 😃
