### ISSUE TITLE
Document hstore extension creation

### ISSUE THREAD

**Issue by saschalalala** [SectorLabs/django-postgres-extra#53]
I don't want my application database users to have superuser permissions so I create them as normal users and configure them to be the owner of the application database. By default, this setup does not work when using django-postgres-extra and the initial migration crashes with 

```
django.db.utils.ProgrammingError: permission denied to create extension "hstore"
HINT:  Must be superuser to create this extension.
```

This is easy to fix, of course, as a psql superuser do:

```
\connect your_database;
CREATE EXTENSION hstore;
```

and I think, it should be documented.

**Comment by Photonios** [comment]
Correct. I'll document this. I am surprised however that you got that error instead of the one in the code which explains this:

https://github.com/SectorLabs/django-postgres-extra/blob/master/psqlextra/backend/base.py#L156-L166

**Comment by Photonios** [comment]
I've documented this behaviour here now: http://django-postgres-extra.readthedocs.io/db-engine/
