### ISSUE TITLE
Insert ignoring conflicts without getting ID back?

### ISSUE THREAD

**Issue by si14** [SectorLabs/django-postgres-extra#54]
There is some pretty fancy logic including locking in the compiler: https://github.com/SectorLabs/django-postgres-extra/blob/47513dbc1b3cde36fcf58c6b2183cbe8d76bd0a1/psqlextra/compiler.py#L150-L169

Do you think it's possible to adjust the API to make it optional? There are cases when the ID isn't needed, so having a CTE and a lock there seems a bit excessive.

**Comment by Photonios** [comment]
Yea I think we can do that. This would have to be a flag, or a separate conflict action.

**Comment by Photonios** [comment]
This is being addressed in v2.

v2 completely removes this (a breaking change) and follows standard PostgreSQL behavior. Stay tuned.
