### ISSUE TITLE
Foreign key RETURNING error

### ISSUE THREAD

**Issue by mbande** [SectorLabs/django-postgres-extra#59]
I have a profile model with has a foreign key like this:
```
user = models.OneToOneField('User', on_delete=models.CASCADE, primary_key=True)
```
trying to ```bulk_insert``` to this model, the following error appears:
```
...
column "user" does not exist
LINE 1: ...id", RETURNING "user"
```
which shows that the query is trying to return ```name``` of the ```pk```.
submited [this](https://github.com/SectorLabs/django-postgres-extra/pull/58) fix

**Comment by Photonios** [comment]
Was fixed in: https://github.com/SectorLabs/django-postgres-extra/pull/58
