### ISSUE TITLE
AttributeError: 'PostgresQuery' object has no attribute 'add_select'

### ISSUE THREAD

**Issue by turukawa** [SectorLabs/django-postgres-extra#60]
I'm new to this module and trying it out with Pandas, Postgres and Django 2.0.2.

I create a queryset, then pass it to `django_pandas` `read_frame` function to convert into a dataframe.

`df = read_frame(MyTable.objects.all())`

At which point I get the following stacktrace:

```
~/miniconda3/envs/pkdev/lib/python3.6/site-packages/django_pandas/io.py in read_frame(qs, fieldnames, index_col, coerce_float, verbose)
    112         recs = list(qs)
    113     else:
--> 114         recs = list(qs.values_list(*fieldnames))
    115 
    116     df = pd.DataFrame.from_records(recs, columns=fieldnames,

~/miniconda3/envs/pkdev/lib/python3.6/site-packages/django/db/models/query.py in values_list(self, flat, named, *fields)
    767                 _fields.append(field)
    768 
--> 769         clone = self._values(*_fields, **expressions)
    770         clone._iterable_class = (
    771             NamedValuesListIterable if named

~/miniconda3/envs/pkdev/lib/python3.6/site-packages/django/db/models/query.py in _values(self, *fields, **expressions)
    735             clone = clone.annotate(**expressions)
    736         clone._fields = fields
--> 737         clone.query.set_values(fields)
    738         return clone
    739 

~/miniconda3/envs/pkdev/lib/python3.6/site-packages/django/db/models/sql/query.py in set_values(self, fields)
   1933 
   1934         self.values_select = tuple(field_names)
-> 1935         self.add_fields(field_names, True)
   1936 
   1937     @property

~/miniconda3/envs/pkdev/lib/python3.6/site-packages/psqlextra/query.py in add_fields(self, field_names, allow_m2m)
    118 
    119             for target in targets:
--> 120                 self.add_select(target.get_col(final_alias))
    121 
    122     def _is_hstore_field(self, field_name: str) -> Tuple[bool, Optional[models.Field]]:

AttributeError: 'PostgresQuery' object has no attribute 'add_select'
```

Not sure what to do to fix this and any suggestions much appreciated.

**Comment by Photonios** [comment]
Doesn't the panda data frame use some Django internal methods? I am not familiar with Panda's so I have no idea how the two interact with each other :(

**Comment by turukawa** [comment]
@Photonios Pandas itself is independent, but the read_frame module of Django Pandas does expect a Django QuerySet object (I think it converts the output to a dict and then to a dataframe). Something the PostgresQuery object doesn't behave as expected.

My 'solution' to the problem was to use a PostgresManager instead of inheriting the PostgresModel.

**Comment by find456789** [comment]
i got this error , in django admin 

postgresql 10,
 django 2.0, 
python 3.6


`

Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/home/item/

Django Version: 2.0.5
Python Version: 3.6.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_celery_results',
 'django.contrib.postgres',
 'psqlextra',
 'apps.home',
 'django_extensions',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback:

File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  574.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  62.             return bound_func(*args, **kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/anaconda3/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  58.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/options.py" in changelist_view
  1570.             cl = self.get_changelist_instance(request)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/options.py" in get_changelist_instance
  705.             self,

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/views/main.py" in __init__
  76.         self.queryset = self.get_queryset(request)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/views/main.py" in get_queryset
  320.          filters_use_distinct) = self.get_filters(request)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/views/main.py" in get_filters
  130.                         self.model, self.model_admin, field_path=field_path

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/filters.py" in create
  157.             return list_filter_class(field, request, params, model, model_admin, field_path=field_path)

File "/anaconda3/lib/python3.6/site-packages/django/contrib/admin/filters.py" in __init__
  402.                                .values_list(field.name, flat=True))

File "/anaconda3/lib/python3.6/site-packages/django/db/models/query.py" in values_list
  769.         clone = self._values(*_fields, **expressions)

File "/anaconda3/lib/python3.6/site-packages/django/db/models/query.py" in _values
  737.         clone.query.set_values(fields)

File "/anaconda3/lib/python3.6/site-packages/django/db/models/sql/query.py" in set_values
  1935.         self.add_fields(field_names, True)

File "/anaconda3/lib/python3.6/site-packages/psqlextra/query.py" in add_fields
  120.                 self.add_select(target.get_col(final_alias))

Exception Type: AttributeError at /admin/home/item/
Exception Value: 'PostgresQuery' object has no attribute 'add_select'


`

**Comment by find456789** [comment]
this is my code:

```
# models.py
class Item(PostgresModel):
    user_id = models.SmallIntegerField('test', blank=True, null=True)
    images = JSONField('images', blank=True, null=True)

# admin.py
@admin.register(Item)
class ItemAdmin(admin.ModelAdmin):
    list_display = ('user_id', 'images',)
    list_filter =  ('user_id', 'images',)
```


so,  when i  remove **user_id** in **list_filter**,  it run normal ,   

when i  add **user_id** in **list_filter**,  i got  **AttributeError: 'PostgresQuery' object has no attribute 'add_select'**

I hope I can help you.

i am sorry,  my english is not very good,

thank you very much

**Comment by Photonios** [comment]
This has been fixed. Django Postgres Extra is now fully compatible with Django 2.0.2.
