### ISSUE TITLE
Extend/add documentation about creating the hstore extension

### ISSUE THREAD

**Issue by atleta** [SectorLabs/django-postgres-extra#80]
Hi,

I think you should add more documentation about creating the hstore extension in the db. You only mention it in the 'working with the code' section, but it's actually something that every user will need to tackle. First for their project (easy enough, you can do it manually or with the provisioning tool at db creation time) and then for the tests.

Now there is an alternate method to using a db superuser for the tests: you can add the extension to the template db used for creating the test db. By default it's `template1` (for every db created), but you can create a separate template and specify that in the `TEST['template']` setting. (Which is indeed `DATABASES['TEST']['template']`, if I'm not mistaken.)

**Comment by Photonios** [comment]
This should happen automatically: https://github.com/SectorLabs/django-postgres-extra/blob/master/psqlextra/backend/base.py#L151

Do you have an example case of where does not happen?

**Comment by atleta** [comment]
I may not have been clear enough: that only happens automatically if you run your code with db superuser privileges. (As you can see in the code, the extension creation may fail which you handle. One of the ways it can fail if the user doesn't have the rights to create an extension.)

See the postgres documentation: 
"Loading an extension requires the same privileges that would be required to create its component objects. For most extensions this means superuser or database owner privileges are needed. "

https://www.postgresql.org/docs/current/sql-createextension.html

As far as I can see, for hstore db owner is inadequate, you need super user.

**Comment by Photonios** [comment]
Thanks! That's a very good point. I will update the documentation shortly to be more clear about this and maybe have a way of disabling the automatic creation. 👍

**Comment by Photonios** [comment]
This is going to be resolved in 2.0. I've documented it more clearly in multiple places and added a setting to disable the behaviour.

https://github.com/SectorLabs/django-postgres-extra/commit/341d246feac3e6cd7df6a31efdcbbaae1ddde53e

https://github.com/SectorLabs/django-postgres-extra/commit/1b16f3a428e4cfd70aac70791e84107cfa07f2df#diff-1a523bd9fa0dbf998008b37579210e12R87
