### ISSUE TITLE
Add RETURNING feature for bulk operations similar to insert_and_get, upsert_and_get

### ISSUE THREAD

**Issue by frenzyk** [SectorLabs/django-postgres-extra#82]
I know, because of [#63](https://github.com/SectorLabs/django-postgres-extra/issues/63) `bulk_insert` is now return nothing. Although as I see it was designed to return only IDs. But when you, for example, using `F()` or passing datetime TZ aware string to DB - you don't know resulting values and have to make an additional SELECT call without RETURNING feature.

**Comment by Photonios** [comment]
I am closing this because this is a duplicate of #63 . Please see that issue for more details.
