### ISSUE TITLE
Updating with .bulk_upsert only if condition is met 

### ISSUE THREAD

**Issue by widnig89** [SectorLabs/django-postgres-extra#85]
I am using `bulk_upsert` already in my project, and it works pretty well.
Now I need to only update the rows in case of the value in specific fields. Let's call it `locked` which is a `BooleanField`. When `locked == true` in a row, I am not allowed to make an update or an insert.
I first thought, that just applying `.filter(locked=False)` will do the job, but I realized `bulk_upsert` always uses the list of rows. 

I played a bit with `F` expressions as well as `Case` and `When`, but it looks like that this isn't supported in `bulk_upsert`

I am also using `conflict_target` for the fields which are unique, but I can't put the `locked` in here. 

Is there a way dealing with such a situation?

**Comment by sarendsen** [comment]
Agreed that this could be really handy. Would be great if we could chain a filter to upserts.

```
obj = (
    Drink.objects
    .on_conflict(['commodity_id'], ConflictAction.UPDATE)
    .upsert(
        conflict_target=['id'],
        fields=dict(name='beer', id=1)
    ).filter(name="wine")
)
```

**Comment by Photonios** [comment]
This works now :)

https://django-postgres-extra.readthedocs.io/en/master/conflict_handling.html#condition
