### ISSUE TITLE
Revert Python 3.6 support

### ISSUE THREAD

**Issue by Mogost** [SectorLabs/django-postgres-extra#91]
https://github.com/SectorLabs/django-postgres-extra/blob/519059b253490e97456747e299fb366b0aaae4d2/setup.py#L61

My reasons for this are:
- 3.6 is official supported till 2021-12.
- The latest Django 3.0 is compatible with 3.6.
- I see no uncompatible with 3.6 code in this project

Also project has wrong classifiers
https://github.com/SectorLabs/django-postgres-extra/blob/519059b253490e97456747e299fb366b0aaae4d2/setup.py#L57

**Comment by Photonios** [comment]
Good point! I've downgraded the requirement and fixed the classifier. I've released a new alpha version on PyPi that brings back Python 3.6 support.

https://pypi.org/project/django-postgres-extra/2.0a14/

I've also set up CI jobs to make sure that Python 3.6 support doesn't break. There are some pieces of code that use `dataclasses`, which were introduced in Python 3.7. I've set up the requirements to install the `dataclasses` package separately if you're installing the package on 3.6.

https://github.com/SectorLabs/django-postgres-extra/blob/master/setup.py#L70

---

On a side note: Please avoid words such as `Please` in issue descriptions. It adds nothing.
