### ISSUE TITLE
Upsert doesn't work with the F() expressions.

### ISSUE THREAD

**Issue by alternativshik** [SectorLabs/django-postgres-extra#94]
F() expressions can only be used to update, not to insert.

So the code something like this won't work. I need to insert new values or update with the increment. 

`DayStat.objects.upsert(
                                        conflict_target=[('date', 'user')],
                                        fields=dict(
                                            date=date, user=user,
                                            clicks=F('clicks') + stat['clicks'],
                                            visits=F('visits') + stat['visits'],
                                        )
                                    )`

**Comment by Photonios** [comment]
How would this need to work on insert? On insert, there's no existing row.

**Comment by alternativshik** [comment]
@Photonios I think  the same as native PG upsert, may be, with another syntax, but like regular PG 
on conflict:

`INSERT INTO table VALUES (SOMENEWVALUE) ON CONFLICT (...) DO UPDATE SET ( value+SOMENEWVALUE )`

**Comment by Photonios** [comment]
This now works, but you have to use a different expression: https://django-postgres-extra.readthedocs.io/en/master/expressions.html#excluded-column
