### ISSUE TITLE
ETA for v2?

### ISSUE THREAD

**Issue by glarrain** [SectorLabs/django-postgres-extra#96]
(sorry for creating an issue for this)

I'm very interested in your library. Since it seems v2 will be a major change (https://github.com/SectorLabs/django-postgres-extra/compare/v1.22...master) over the latest stable version I'd love to know when can a release be expected, or some order magnitude of what's missing.

**Comment by ryanhiebert** [comment]
I'm getting ready to integrate this into my project, for the upsert capability. Would it be recommended to use the current stable version, or would you think it's better to use the v2 code?

**Comment by kingbuzzman** [comment]
@Photonios ? Any update?

**Comment by warmwaffles** [comment]
@Photonios any updates?

**Comment by fladi** [comment]
2.0 was released but there is no accompanying git tag. Could someone push it to github.

**Comment by Photonios** [comment]
Yes! v2.0 is out. I've created a Github release + tag here: https://github.com/SectorLabs/django-postgres-extra/releases/tag/v2.0

Sorry for the delay on that.
